"""Online-only, case-aware response composition for every user-facing turn."""

from __future__ import annotations

import json
import re
from typing import Any

from pydantic import BaseModel, Field, ValidationError

from backend.ai.dialogue import redact_sensitive_text
from backend.ai.provider import AIProvider, AIProviderError, get_consultation_provider


class OnlineModelUnavailableError(RuntimeError):
    """Raised when a user-facing reply cannot be generated by the online model."""

    def __init__(self, code: str, message: str) -> None:
        self.code = code
        super().__init__(message)


class OnlineReplyDraft(BaseModel):
    reply: str = Field(min_length=1, max_length=4000)
    asked_fact_ids: list[str] = Field(default_factory=list)


ONLINE_REPLY_SCHEMA: dict[str, Any] = {
    "type": "object",
    "properties": {
        "reply": {
            "type": "string",
            "minLength": 1,
            "maxLength": 4000,
        },
        "asked_fact_ids": {
            "type": "array",
            "maxItems": 1,
            "items": {"type": "string"},
        },
    },
    "required": ["reply", "asked_fact_ids"],
}


# These are presentation templates that should never be copied into an online
# answer. Safety content itself is not banned; only the mechanical wrappers are.
_BANNED_TEMPLATE_PHRASES = (
    "**先处理紧急事项**",
    "你现在最希望得到什么结果",
    "我先和你一起把情况理清",
    "情况我已经大致理清了",
    "按现有信息，可以先这样推进",
    "为了把报告补完整，还想请你补充",
    "请再补充一下相关情况。",
)
_ARTICLE_PATTERN = re.compile(r"第[0-9零〇一二两三四五六七八九十百千万]+条")


def _short(value: Any, limit: int = 180) -> str:
    return re.sub(r"\s+", " ", redact_sensitive_text(str(value or ""))).strip()[:limit]


def _state_context(state, message: str, raw_reply: str) -> dict[str, Any]:
    facts = {
        key: _short(value)
        for key, value in state.facts.items()
        if value not in (None, "")
    }
    evidence = [
        {
            "name": _short(task.name, 120),
            "proves": _short(task.proves, 180),
            "status": _short(task.status, 80),
            "source_refs": [_short(ref, 80) for ref in task.source_refs[:3]],
        }
        for task in state.consultation.evidence_tasks[:12]
    ]
    laws = [
        {
            "source_id": _short(item.get("source_id"), 100),
            "law_name": _short(item.get("law_name"), 120),
            "article": _short(item.get("article"), 80),
            "summary": _short(item.get("summary"), 220),
        }
        for item in state.consultation.knowledge_passages[:8]
    ]
    action = state.current_action.name if state.current_action is not None else ""
    return {
        "本轮用户原话": _short(message, 1200),
        "案件最初叙述": _short(state.user_narrative, 1800),
        "领域": _short(state.case_type, 80),
        "咨询者已陈述事实": facts,
        "双方争议或冲突": [
            {_short(key, 80): _short(value, 240) for key, value in conflict.items()}
            for conflict in state.consultation.conflicts[:8]
        ],
        "已上传或自述材料": evidence,
        "暂时无法提供的材料": [_short(item, 120) for item in state.unavailable_evidence[:12]],
        "证据缺口": [
            {
                "name": _short(gap.name, 120),
                "status": _short(gap.status.value if hasattr(gap.status, "value") else gap.status, 80),
                "reason": _short(gap.reason, 220),
            }
            for gap in state.evidence_gaps[:12]
        ],
        "用户目标和限制": {
            "目标": facts.get("goal", ""),
            "限制": facts.get("constraints", ""),
        },
        "程序进展": facts.get("procedure", ""),
        "紧急事项（只有这些才可表达紧急建议）": [
            _short(item, 300) for item in state.consultation.urgent_actions[:6]
        ],
        "本轮规则动作": action,
        "规则动作原因": _short(state.current_reason, 300),
        "结构化个案分析草稿": _short(state.consultation.analysis, 1800),
        "结构化追问草稿": _short(state.consultation.follow_up, 500),
        "个案化行动步骤草稿": [
            {
                "title": _short(step.title, 140),
                "when": _short(step.when, 180),
                "channel": _short(step.channel, 180),
                "materials": [_short(item, 120) for item in step.materials[:8]],
                "instructions": [_short(item, 220) for item in step.instructions[:4]],
                "completion": _short(step.completion, 180),
                "fallback": _short(step.fallback, 220),
            }
            for step in state.consultation.tailored_steps[:4]
        ],
        "主要法律问题": [_short(item, 180) for item in state.legal_issues[:8]],
        "对方可能抗辩": [
            _short(item, 240)
            for item in state.opponent_analysis.get("arguments", [])[:6]
        ],
        "待补事实ID（只能从这里选择，最多一个）": list(state.pending_fact_ids[:1]),
        "待补事实问题（仅作事实含义参考，不得原样套用）": [
            _short(item, 300) for item in state.pending_questions[:2]
        ],
        "法源（仅可引用这些来源）": laws,
        "规则层草案（只作信息参考，禁止照抄其衔接词）": _short(raw_reply, 3000),
    }


def _case_anchor_terms(state) -> list[str]:
    terms: list[str] = []
    for key in ("amount", "event_time", "location", "goal", "parties", "details", "procedure"):
        value = str(state.facts.get(key, "")).strip()
        if not value:
            continue
        if len(value) <= 80:
            terms.append(value)
        # Numbers and named locations should survive paraphrasing exactly.
        numbers = re.findall(r"[0-9一二两三四五六七八九十百千万]+(?:万元|元|万|个月|年|日|号)?", value)
        terms.extend(item for item in numbers if len(item) >= 2)
    return list(dict.fromkeys(item for item in terms if len(item) >= 2))[:18]


def _validation_issues(draft: OnlineReplyDraft, state) -> list[str]:
    reply = draft.reply.strip()
    issues: list[str] = []
    for phrase in _BANNED_TEMPLATE_PHRASES:
        if phrase in reply:
            issues.append(f"不得使用固定衔接词：{phrase}")
    allowed = set(state.pending_fact_ids)
    if len(draft.asked_fact_ids) > 1:
        issues.append("每轮最多追问一个事实")
    if any(item not in allowed for item in draft.asked_fact_ids):
        issues.append("追问了本轮不允许的事实ID")
    anchors = _case_anchor_terms(state)
    if anchors and not any(anchor in reply for anchor in anchors):
        issues.append("回复没有提到当前案件中的具体事实、目标或材料")
    mentioned_articles = set(_ARTICLE_PATTERN.findall(reply))
    if mentioned_articles:
        allowed_articles = {
            str(item.get("article", "")).strip()
            for item in state.consultation.knowledge_passages
            if item.get("article")
        }
        if not mentioned_articles.issubset(allowed_articles):
            issues.append("回复引用了本轮上下文没有提供的法条")
    urgent = state.consultation.urgent_actions
    if urgent:
        urgent_text = " ".join(urgent)
        hint_groups = (
            ("安全", "警方", "就医", "医院", "律师", "法律援助"),
            ("截止", "期限", "送达", "文书", "受理"),
        )
        group = hint_groups[1] if any(word in urgent_text for word in hint_groups[1]) else hint_groups[0]
        if not any(word in reply for word in group):
            issues.append("回复没有覆盖规则层标记的紧急处理重点")
    return issues


def _prompt(context: dict[str, Any], feedback: list[str] | None = None) -> str:
    feedback_text = ""
    if feedback:
        feedback_text = "\n校验反馈（上一版未通过）：\n- " + "\n- ".join(feedback)
    return (
        "你是 LexPilot 的在线法律咨询回复顾问。你只能根据下面这份案件上下文回答，"
        "像真实、耐心、务实的法律顾问一样直接回应本轮用户，不自称律师或律所。\n"
        "先回答用户这一次真正问的事，再说明判断依据、对当前案件的影响和现在能做的动作。"
        "不要把回复写成固定问卷、模板清单或系统日志；不要使用固定衔接词或通用标题。"
        "尤其不要出现‘先处理紧急事项’、‘你现在最希望得到什么结果’、‘我先和你一起把情况理清’等话术。"
        "只有上下文列出的紧急事项才可以给出安全或期限提醒，并要用本案事实说明为什么。"
        "需要补事实时最多问一个问题，说明这个问题会改变哪一个判断；问题已经回答、拒答或不知道的不要重问。"
        "保留用户提供的数字、日期、身份和材料名称，不把推测写成事实。不得保证结果、编造法条、地址、期限或胜率。"
        "法律来源只能引用上下文允许的来源；没有可靠来源时明确说需要核对。可以使用简短段落或少量项目符号，"
        "但每一项都必须与本案有关。只返回 JSON 对象，格式为 {reply:string, asked_fact_ids:string[]}。"
        f"{feedback_text}\n\n案件上下文：\n{json.dumps(context, ensure_ascii=False)}"
    )


def compose_online_reply(
    message: str,
    state,
    raw_reply: str,
    *,
    provider: AIProvider | None = None,
) -> str:
    """Generate and validate the only user-facing reply for one turn."""

    semantic_provider = provider or get_consultation_provider()
    if semantic_provider is None:
        raise OnlineModelUnavailableError(
            "not_configured",
            "联网法律分析未配置有效模型密钥。",
        )

    context = _state_context(state, message, raw_reply)
    feedback: list[str] = []
    for attempt in range(2):
        try:
            value = semantic_provider.generate_json(
                _prompt(context, feedback),
                ONLINE_REPLY_SCHEMA,
                max_output_tokens=2200,
                thinking_level=None,
            )
            draft = OnlineReplyDraft.model_validate(value)
        except AIProviderError as exc:
            raise OnlineModelUnavailableError(
                getattr(exc, "code", "temporarily_unavailable"),
                "联网法律分析请求失败，请稍后重试。",
            ) from exc
        except (ValidationError, TypeError, ValueError) as exc:
            feedback = ["模型没有返回符合要求的 JSON 结构。"]
            if attempt == 0:
                continue
            raise OnlineModelUnavailableError(
                "invalid_response",
                "联网法律分析返回内容未通过结构校验。",
            ) from exc

        feedback = _validation_issues(draft, state)
        if not feedback:
            state.consultation.semantic_status = "已由联网模型结合本案事实生成回复。"
            return draft.reply.strip()
    raise OnlineModelUnavailableError(
        "invalid_response",
        "联网法律分析回复未通过个案化与安全校验。",
    )
